spring:
  cloud:
    config:
      server:
        git: uri:https://github.com/ivan920605/PlayConfigurationFiles.git
spring:
  application:
    name: configserver
spring:
  application: 
    description: Hello,Spring Cloud Config Server App!

server:
    port: 8888